name = "keepspace"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "keepspace-db"
database_id = "a2b7621f-c418-4583-b4e0-0a5023781d79"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "keepspace-documents"
preview_bucket_name = "keepspace-documents-local"
